controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    #API Documentation with Swagger
    app.swagger_ui:
        path: /api/doc
        methods: GET
        defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
